"""add order and position tracking

Revision ID: 041f37acf8c2
Revises: 77924f83d9be
Create Date: 2025-12-07 20:59:15.055157

"""

from __future__ import annotations

import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = "041f37acf8c2"
down_revision = "77924f83d9be"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "position",
        sa.Column("ticker", sa.String(length=16), nullable=True),
        sa.Column("side", sa.String(length=8), nullable=True),
        sa.Column("qty", sa.Float(), nullable=True),
        sa.Column("avg_entry_price", sa.Float(), nullable=True),
        sa.Column("cost_basis", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=8), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_position")),
    )
    op.create_table(
        "order",
        sa.Column("client_order_id", sa.String(), nullable=True),
        sa.Column("vendor_order_id", sa.String(), nullable=True),
        sa.Column("ticker", sa.String(length=16), nullable=True),
        sa.Column("vendor_asset_id", sa.String(length=64), nullable=True),
        sa.Column("side", sa.String(length=8), nullable=True),
        sa.Column("qty", sa.Float(), nullable=True),
        sa.Column("type", sa.String(length=16), nullable=True),
        sa.Column("time_in_force", sa.String(length=8), nullable=True),
        sa.Column("extended_hours", sa.Boolean(), nullable=True),
        sa.Column("limit_price", sa.Float(), nullable=True),
        sa.Column("stop_price", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=True),
        sa.Column("filled_at", sa.DateTime(), nullable=True),
        sa.Column("filled_qty", sa.Float(), nullable=True),
        sa.Column("filled_avg_price", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("position_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["position_id"],
            ["position.id"],
            name=op.f("fk_order_to_position_id_on_position"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order")),
    )
    op.create_index(
        op.f("ix_order_client_order_id"),
        "order",
        ["client_order_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_order_vendor_order_id"),
        "order",
        ["vendor_order_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "stats",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "stats",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_index(op.f("ix_order_vendor_order_id"), table_name="order")
    op.drop_index(op.f("ix_order_client_order_id"), table_name="order")
    op.drop_table("order")
    op.drop_table("position")
    op.drop_table("intraday")
    # ### end Alembic commands ###
