"""add stats model

Revision ID: 2f83b45aab18
Revises: a801fd4a0f6c
Create Date: 2025-06-01 11:41:45.693667

"""

from __future__ import annotations

import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = "2f83b45aab18"
down_revision = "a801fd4a0f6c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stats",
        sa.Column("symbol", sa.String(), nullable=True),
        sa.Column("day", sa.Date(), nullable=True),
        sa.Column("stats", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stats")),
        sa.UniqueConstraint("symbol", "day", name=op.f("uq_stats_symbol")),
    )
    op.create_index(op.f("ix_stats_day"), "stats", ["day"], unique=False)
    op.create_index(op.f("ix_stats_symbol"), "stats", ["symbol"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_stats_symbol"), table_name="stats")
    op.drop_index(op.f("ix_stats_day"), table_name="stats")
    op.drop_table("stats")
    # ### end Alembic commands ###
