"""add freq to stats table

Revision ID: 77924f83d9be
Revises: 2f83b45aab18
Create Date: 2025-06-16 05:57:40.760946

"""

from __future__ import annotations

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "77924f83d9be"
down_revision = "2f83b45aab18"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    freq_type = sa.Enum(
        "min_1",
        "min_2",
        "min_5",
        "min_10",
        "min_15",
        "min_30",
        "hour",
        "day",
        "week",
        "month",
        "quarter",
        "year",
        name="freq",
    )
    freq_type.create(op.get_bind(), checkfirst=True)
    op.add_column("stats", sa.Column("freq", freq_type, nullable=True))
    op.execute(sa.text("UPDATE stats SET freq = 'day'::freq"))
    op.alter_column("stats", "freq", nullable=False)
    op.alter_column("stats", "symbol", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("stats", "day", existing_type=sa.DATE(), nullable=False)
    op.drop_constraint("uq_stats_symbol", "stats", type_="unique")
    op.create_unique_constraint(
        op.f("uq_stats_symbol"), "stats", ["symbol", "day", "freq"]
    )
    op.create_index(op.f("ix_stats_freq"), "stats", ["freq"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_stats_freq"), table_name="stats")
    op.drop_constraint(op.f("uq_stats_symbol"), "stats", type_="unique")
    op.create_unique_constraint("uq_stats_symbol", "stats", ["symbol", "day"])
    op.alter_column("stats", "day", existing_type=sa.DATE(), nullable=True)
    op.alter_column("stats", "symbol", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("stats", "freq")
    # ### end Alembic commands ###
