"""create models

Revision ID: df8fbea63dd7
Revises:
Create Date: 2025-04-16 19:04:27.168866

"""

from __future__ import annotations

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "df8fbea63dd7"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "currency",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("iso_code", sa.String(length=3), nullable=False),
        sa.Column("iso_name", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=32), nullable=True),
        sa.Column("plural", sa.String(length=32), nullable=True),
        sa.Column("symbol", sa.String(length=8), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_currency")),
        sa.UniqueConstraint("plural", name=op.f("uq_currency_plural")),
    )
    op.create_index(op.f("ix_currency_iso_code"), "currency", ["iso_code"], unique=True)
    op.create_index(op.f("ix_currency_iso_name"), "currency", ["iso_name"], unique=True)
    op.create_index(op.f("ix_currency_name"), "currency", ["name"], unique=True)
    op.create_table(
        "data_item",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("key", sa.String(length=32), nullable=False),
        sa.Column("update_frequency", sa.String(length=32), nullable=False),
        sa.Column("update_at", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_item")),
    )
    op.create_table(
        "data_vendor",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("key", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("priority", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_vendor")),
    )
    op.create_index(op.f("ix_data_vendor_key"), "data_vendor", ["key"], unique=True)
    op.create_index(op.f("ix_data_vendor_name"), "data_vendor", ["name"], unique=True)
    op.create_table(
        "exchange",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("abbrev", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exchange")),
        sa.UniqueConstraint("abbrev", name=op.f("uq_exchange_abbrev")),
        sa.UniqueConstraint("name", name=op.f("uq_exchange_name")),
    )
    op.create_table(
        "index",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("ticker", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_index")),
    )
    op.create_index(op.f("ix_index_name"), "index", ["name"], unique=True)
    op.create_index(op.f("ix_index_ticker"), "index", ["ticker"], unique=True)
    op.create_table(
        "sector",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sector")),
    )
    op.create_index(op.f("ix_sector_name"), "sector", ["name"], unique=True)
    op.create_table(
        "watchlist",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_watchlist")),
    )
    op.create_index(op.f("ix_watchlist_name"), "watchlist", ["name"], unique=True)
    op.create_table(
        "country",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("iso_code", sa.String(length=2), nullable=False),
        sa.Column("iso_code3", sa.String(length=3), nullable=False),
        sa.Column("iso_name", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=True),
        sa.Column("native_name", sa.String(length=64), nullable=True),
        sa.Column("currency_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["currency_id"], ["currency.id"], name=op.f("fk_country_currency_id_currency")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_country")),
        sa.UniqueConstraint("native_name", name=op.f("uq_country_native_name")),
    )
    op.create_index(op.f("ix_country_iso_code"), "country", ["iso_code"], unique=True)
    op.create_index(op.f("ix_country_iso_code3"), "country", ["iso_code3"], unique=True)
    op.create_index(op.f("ix_country_iso_name"), "country", ["iso_name"], unique=True)
    op.create_index(op.f("ix_country_name"), "country", ["name"], unique=True)
    op.create_table(
        "data_item_vendor",
        sa.Column("data_item_id", sa.BigInteger(), nullable=False),
        sa.Column("data_vendor_id", sa.BigInteger(), nullable=False),
        sa.Column("priority", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["data_item_id"],
            ["data_item.id"],
            name=op.f("fk_data_item_vendor_data_item_id_data_item"),
        ),
        sa.ForeignKeyConstraint(
            ["data_vendor_id"],
            ["data_vendor.id"],
            name=op.f("fk_data_item_vendor_data_vendor_id_data_vendor"),
        ),
        sa.PrimaryKeyConstraint(
            "data_item_id", "data_vendor_id", name=op.f("pk_data_item_vendor")
        ),
    )
    op.create_table(
        "index_data_vendor",
        sa.Column("index_id", sa.BigInteger(), nullable=False),
        sa.Column("data_vendor_id", sa.BigInteger(), nullable=False),
        sa.Column("ticker", sa.String(length=16), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["data_vendor_id"],
            ["data_vendor.id"],
            name=op.f("fk_index_data_vendor_data_vendor_id_data_vendor"),
        ),
        sa.ForeignKeyConstraint(
            ["index_id"], ["index.id"], name=op.f("fk_index_data_vendor_index_id_index")
        ),
        sa.PrimaryKeyConstraint(
            "index_id", "data_vendor_id", name=op.f("pk_index_data_vendor")
        ),
    )
    op.create_table(
        "industry",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("sector_id", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["sector_id"], ["sector.id"], name=op.f("fk_industry_sector_id_sector")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_industry")),
    )
    op.create_index(op.f("ix_industry_name"), "industry", ["name"], unique=True)
    op.create_table(
        "market",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("abbrev", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("country_id", sa.BigInteger(), nullable=False),
        sa.Column("exchange_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["country_id"], ["country.id"], name=op.f("fk_market_country_id_country")
        ),
        sa.ForeignKeyConstraint(
            ["exchange_id"], ["exchange.id"], name=op.f("fk_market_exchange_id_exchange")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_market")),
    )
    op.create_table(
        "asset",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("ticker", sa.String(), nullable=False),
        sa.Column("market_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["market_id"], ["market.id"], name=op.f("fk_asset_market_id_market")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_asset")),
    )
    op.create_index(op.f("ix_asset_ticker"), "asset", ["ticker"], unique=True)
    op.create_table(
        "asset_data_vendor",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("asset_id", sa.BigInteger(), nullable=False),
        sa.Column("data_vendor_id", sa.BigInteger(), nullable=False),
        sa.Column("ticker", sa.String(), nullable=True),
        sa.Column("minutely_last_updated", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("daily_last_updated", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("weekly_last_updated", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("monthly_last_updated", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"], ["asset.id"], name=op.f("fk_asset_data_vendor_asset_id_asset")
        ),
        sa.ForeignKeyConstraint(
            ["data_vendor_id"],
            ["data_vendor.id"],
            name=op.f("fk_asset_data_vendor_data_vendor_id_data_vendor"),
        ),
        sa.PrimaryKeyConstraint(
            "id", "asset_id", "data_vendor_id", name=op.f("pk_asset_data_vendor")
        ),
    )
    op.create_table(
        "equity",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("company_name", sa.String(), nullable=False),
        sa.Column("company_description", sa.Text(), nullable=True),
        sa.Column("sector_id", sa.BigInteger(), nullable=True),
        sa.Column("industry_id", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(["id"], ["asset.id"], name=op.f("fk_equity_id_asset")),
        sa.ForeignKeyConstraint(
            ["industry_id"], ["industry.id"], name=op.f("fk_equity_industry_id_industry")
        ),
        sa.ForeignKeyConstraint(
            ["sector_id"], ["sector.id"], name=op.f("fk_equity_sector_id_sector")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_equity")),
    )
    op.create_index(
        op.f("ix_equity_company_name"), "equity", ["company_name"], unique=False
    )
    op.create_table(
        "watchlist_asset",
        sa.Column("asset_id", sa.BigInteger(), nullable=False),
        sa.Column("watchlist_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"], ["asset.id"], name=op.f("fk_watchlist_asset_asset_id_asset")
        ),
        sa.ForeignKeyConstraint(
            ["watchlist_id"],
            ["watchlist.id"],
            name=op.f("fk_watchlist_asset_watchlist_id_watchlist"),
        ),
        sa.PrimaryKeyConstraint(
            "asset_id", "watchlist_id", name=op.f("pk_watchlist_asset")
        ),
    )
    op.create_table(
        "equity_index",
        sa.Column("equity_id", sa.BigInteger(), nullable=False),
        sa.Column("index_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["equity_id"], ["equity.id"], name=op.f("fk_equity_index_equity_id_equity")
        ),
        sa.ForeignKeyConstraint(
            ["index_id"], ["index.id"], name=op.f("fk_equity_index_index_id_index")
        ),
        sa.PrimaryKeyConstraint("equity_id", "index_id", name=op.f("pk_equity_index")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("equity_index")
    op.drop_table("watchlist_asset")
    op.drop_index(op.f("ix_equity_company_name"), table_name="equity")
    op.drop_table("equity")
    op.drop_table("asset_data_vendor")
    op.drop_index(op.f("ix_asset_ticker"), table_name="asset")
    op.drop_table("asset")
    op.drop_table("market")
    op.drop_index(op.f("ix_industry_name"), table_name="industry")
    op.drop_table("industry")
    op.drop_table("index_data_vendor")
    op.drop_table("data_item_vendor")
    op.drop_index(op.f("ix_country_name"), table_name="country")
    op.drop_index(op.f("ix_country_iso_name"), table_name="country")
    op.drop_index(op.f("ix_country_iso_code3"), table_name="country")
    op.drop_index(op.f("ix_country_iso_code"), table_name="country")
    op.drop_table("country")
    op.drop_index(op.f("ix_watchlist_name"), table_name="watchlist")
    op.drop_table("watchlist")
    op.drop_index(op.f("ix_sector_name"), table_name="sector")
    op.drop_table("sector")
    op.drop_index(op.f("ix_index_ticker"), table_name="index")
    op.drop_index(op.f("ix_index_name"), table_name="index")
    op.drop_table("index")
    op.drop_table("exchange")
    op.drop_index(op.f("ix_data_vendor_name"), table_name="data_vendor")
    op.drop_index(op.f("ix_data_vendor_key"), table_name="data_vendor")
    op.drop_table("data_vendor")
    op.drop_table("data_item")
    op.drop_index(op.f("ix_currency_name"), table_name="currency")
    op.drop_index(op.f("ix_currency_iso_name"), table_name="currency")
    op.drop_index(op.f("ix_currency_iso_code"), table_name="currency")
    op.drop_table("currency")
    # ### end Alembic commands ###
